# Generated by Django 5.2.5 on 2026-03-16 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coastal_changes', '0001_initial'),
        ('datasets', '0042_alter_cluster_options_alter_pmtilesdataset_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoastalChangesPMTilesDataset',
            fields=[
            ],
            options={
                'verbose_name': 'Coastal Changes PMTiles',
                'verbose_name_plural': 'Coastal Changes PMTiles',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('datasets.pmtilesdataset',),
        ),
        migrations.CreateModel(
            name='CoastalChangesVectorDataset',
            fields=[
            ],
            options={
                'verbose_name': 'Coastal Changes Vector',
                'verbose_name_plural': 'Coastal Changes Vector',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('datasets.vectordataset',),
        ),
    ]
