# Generated by Django 5.2.5 on 2026-03-16 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datasets', '0042_alter_cluster_options_alter_pmtilesdataset_options_and_more'),
        ('land_accounts', '0003_add_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandAccountsPMTilesDataset',
            fields=[
            ],
            options={
                'verbose_name': 'Land Accounts PMTiles',
                'verbose_name_plural': 'Land Accounts PMTiles',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('datasets.pmtilesdataset',),
        ),
        migrations.CreateModel(
            name='LandAccountsVectorDataset',
            fields=[
            ],
            options={
                'verbose_name': 'Land Accounts Vector',
                'verbose_name_plural': 'Land Accounts Vector',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('datasets.vectordataset',),
        ),
    ]
