# Generated by Django 5.2.5 on 2026-03-17 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('climate', '0001_initial'),
        ('datasets', '0043_alter_pmtilesdataset_climate_modules_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClimateVectorItem',
            fields=[
            ],
            options={
                'verbose_name': 'Vector item',
                'verbose_name_plural': 'Vector items',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('datasets.vectoritem',),
        ),
    ]
