/**
 * Bar chart showing land cover class percentages from the uploaded raster.
 * Uses shared useLandCoverStats (same dataset as ClimateKeyIndicators).
 * Data from /media/landcover_stats.json (generated by: python manage.py generate_landcover_stats).
 */
import { useMemo } from "react";
import Highcharts from "highcharts";
import HighchartsReact from "highcharts-react-official";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import {
  LAND_COVER_CLASS_ORDER,
  LAND_COVER_PIXEL_COLORS,
} from "@/config/landCover";
import { useColorMode } from "@/components/ui/color-mode";
import { useDeferredArea } from "@/hooks/useDeferredArea";
import { useDateStore } from "@/store/date-store";
import { useHighchartsTheme } from "@/hooks/useHighchartsTheme";
import { useLayerStore } from "@/store/layer-store";
import { useScenario } from "@/hooks/useScenario";
import { useLandCoverStats } from "@/hooks/useLandCoverStats";

export function LandCoverTotalsChart() {
  const theme = useHighchartsTheme();
  const { year } = useDateStore();
  useColorMode(); // theme available via useHighchartsTheme
  const { layers } = useLayerStore();
  const scenario = useScenario();
  const { province } = useDeferredArea();
  const { data, total, stats, isLoading } = useLandCoverStats();

  const hasRasterLayer = layers.split(",").some((l) => l.startsWith("r"));
  const isClimate = scenario.uiConfig.sidebarLayout === "climate";

  const palette = useMemo(() => {
    return LAND_COVER_CLASS_ORDER.map(
      (_, i) => LAND_COVER_PIXEL_COLORS[String(i)] ?? "#888",
    );
  }, []);

  const chartOptions = useMemo((): Highcharts.Options => {
    return Highcharts.merge(theme, {
      chart: { type: "column" },
      title: { text: undefined },
      xAxis: {
        categories: data.map((d) => d.name),
        labels: {
          rotation: -45,
          style: { fontSize: "10px" },
        },
      },
      yAxis: {
        min: 0,
        max: 100,
        title: { text: "Share (%)", style: { fontSize: "10px" } },
        labels: {
          formatter: function (this: Highcharts.AxisLabelsFormatterContextObject) {
            return `${this.value}%`;
          },
        },
      },
      plotOptions: {
        column: {
          borderRadius: 4,
          dataLabels: {
            enabled: true,
            format: "{y}%",
            style: { fontSize: "9px" },
          },
        },
      },
      series: [
        {
          type: "column",
          name: "Land cover",
          data: data.map((d, i) => ({
            y: d.y,
            color: palette[i],
          })),
          showInLegend: false,
        },
      ],
      tooltip: {
        formatter: function (this: { point: Highcharts.Point }) {
          const idx = this.point.index ?? 0;
          const d = data[idx];
          const name = d?.name ?? "Unknown";
          const area = d?.area ?? 0;
          return `<b>${name}</b><br/>${this.point.y}% (${area.toFixed(1)} km²)`;
        },
      },
      legend: { enabled: false },
    });
  }, [theme, data, palette]);

  if (!isClimate || !hasRasterLayer) return null;

  if (isLoading || !stats) {
    return (
      <Card className="overflow-hidden border-border/60 bg-card/50">
        <CardHeader className="pb-2">
          <CardTitle className="text-sm font-medium">
            Land cover totals {year}
          </CardTitle>
          <p className="text-xs text-muted-foreground">
            Run <code className="rounded bg-muted px-1">python manage.py generate_landcover_stats</code> after
            generating tiles.
          </p>
        </CardHeader>
      </Card>
    );
  }

  return (
    <Card className="overflow-hidden border-border/60 bg-card/50">
      <CardHeader className="pb-2">
        <CardTitle className="text-sm font-medium">
          Land cover totals {year}
        </CardTitle>
        <p className="text-xs text-muted-foreground">
          {province || "National"} · {total.toFixed(1)} km² total
        </p>
      </CardHeader>
      <CardContent className="px-4 pb-4 pt-0">
        <HighchartsReact
          highcharts={Highcharts}
          options={chartOptions}
          containerProps={{ style: { width: "100%", height: 220 } }}
        />
      </CardContent>
    </Card>
  );
}
