# Generated by Django 5.2.5 on 2026-03-17 02:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldCheckRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('verified', 'Verified'), ('adjusted', 'Adjusted'), ('rejected', 'Rejected')], db_index=True, max_length=20)),
                ('observed_value', models.FloatField(blank=True, help_text='Field-observed value when status is adjusted.', null=True)),
                ('notes', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(limit_choices_to={'model__in': ('tabularitem', 'vectoritem')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('verified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='field_check_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Field Check Record',
                'verbose_name_plural': 'Field Check Records',
                'ordering': ['-verified_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='field_check_content_487f34_idx')],
            },
        ),
    ]
