# Generated by Django 5.2.5 on 2026-03-17 01:59

import vbos.feedback.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_add_feedback_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to=vbos.feedback.models.feedback_screenshot_path),
        ),
    ]
