site_name: vbos
site_description: VBOS Django application and data services
site_dir: site
copyright: Copyright &copy; 2020.
dev_addr: 0.0.0.0:8015

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
